package services
import("errors";"time";"backend-notaris-go/database";"backend-notaris-go/dto/request";"backend-notaris-go/models";"backend-notaris-go/repositories";"gorm.io/gorm")
var ErrDuplicatePekerjaanKategori=errors.New("Kategori pekerjaan tidak boleh sama")
type PekerjaanService struct{repo *repositories.PekerjaanRepository}
func NewPekerjaanService()*PekerjaanService{return &PekerjaanService{repo:repositories.NewPekerjaanRepository()}}
type PekerjaanHargaResponse struct{ID uint `json:"id"`;Harga string `json:"harga"`;KategoriPekerjaanID uint `json:"kategori_pekerjaan_id"`;EstimasiWaktu string `json:"estimasi_waktu"`}
type PekerjaanAtributResponse struct{ID uint `json:"id"`;Atribut string `json:"atribut"`}
type PekerjaanProsesResponse struct{ID uint `json:"id"`;Nama string `json:"nama"`;Detail string `json:"detail"`;Atribut []PekerjaanAtributResponse `json:"atribut"`}
type PekerjaanResponse struct{ID uint `json:"id"`;Nama string `json:"nama"`;Harga []PekerjaanHargaResponse `json:"harga"`;Proses []PekerjaanProsesResponse `json:"proses"`}
func(s *PekerjaanService)GetAll(k string)(interface{},error){if k=="notaris"{x,e:=s.repo.ListNotaris();if e!=nil{return nil,e};return s.attachNotaris(x)};x,e:=s.repo.ListPPAT();if e!=nil{return nil,e};return s.attachPPAT(x)}
func(s *PekerjaanService)GetByID(k string,id uint)(interface{},error){if k=="notaris"{x,e:=s.repo.FindNotaris(id);if e!=nil{return nil,e};a,e:=s.attachNotaris([]models.PekerjaanNotaris{*x});if e!=nil{return nil,e};return a[0],nil};x,e:=s.repo.FindPPAT(id);if e!=nil{return nil,e};a,e:=s.attachPPAT([]models.PekerjaanPPAT{*x});if e!=nil{return nil,e};return a[0],nil}
func(s *PekerjaanService)Create(k string,q request.PekerjaanRequest,u uint)(interface{},error){if e:=validateHarga(q.Harga);e!=nil{return nil,e};now:=time.Now();var id uint;e:=database.DB.Transaction(func(tx *gorm.DB)error{if k=="notaris"{x:=&models.PekerjaanNotaris{Nama:q.Nama,CreatedBy:&u,CreatedAt:&now,Status:1};if e:=tx.Create(x).Error;e!=nil{return e};id=x.ID;return s.saveNotaris(tx,id,q,u,now)};x:=&models.PekerjaanPPAT{Nama:q.Nama,CreatedBy:&u,CreatedAt:&now,Status:1};if e:=tx.Create(x).Error;e!=nil{return e};id=x.ID;return s.savePPAT(tx,id,q,u,now)});if e!=nil{return nil,e};return s.GetByID(k,id)}
func(s *PekerjaanService)Update(k string,id uint,q request.PekerjaanRequest,u uint)(interface{},error){if e:=validateHarga(q.Harga);e!=nil{return nil,e};now:=time.Now();e:=database.DB.Transaction(func(tx *gorm.DB)error{if k=="notaris"{x,e:=s.repo.FindNotaris(id);if e!=nil{return e};x.Nama=q.Nama;x.UpdatedBy=&u;x.UpdatedAt=&now;x.Status=1;if e=tx.Save(x).Error;e!=nil{return e};if e=s.repo.DeleteNotarisChildren(tx,id);e!=nil{return e};return s.saveNotaris(tx,id,q,u,now)};x,e:=s.repo.FindPPAT(id);if e!=nil{return e};x.Nama=q.Nama;x.UpdatedBy=&u;x.UpdatedAt=&now;x.Status=1;if e=tx.Save(x).Error;e!=nil{return e};if e=s.repo.DeletePPATChildren(tx,id);e!=nil{return e};return s.savePPAT(tx,id,q,u,now)});if e!=nil{return nil,e};return s.GetByID(k,id)}
func(s *PekerjaanService)Delete(k string,id,u uint)error{now:=time.Now();return database.DB.Transaction(func(tx *gorm.DB)error{if k=="notaris"{if _,e:=s.repo.FindNotaris(id);e!=nil{return e};if e:=s.repo.DeactivateNotaris(tx,id,u,now);e!=nil{return e};if e:=s.repo.DeactivateNotarisChildren(tx,id,u,now);e!=nil{return e};if e:=s.repo.DeactivateNotarisHarga(tx,id,u,now);e!=nil{return e};return s.repo.DeactivateNotarisAtribut(tx,id,u,now)};if _,e:=s.repo.FindPPAT(id);e!=nil{return e};if e:=s.repo.DeactivatePPAT(tx,id,u,now);e!=nil{return e};if e:=s.repo.DeactivatePPATChildren(tx,id,u,now);e!=nil{return e};if e:=s.repo.DeactivatePPATHarga(tx,id,u,now);e!=nil{return e};return s.repo.DeactivatePPATAtribut(tx,id,u,now)})}
func validateHarga(x []request.PekerjaanHargaRequest)error{seen:=map[uint]bool{};for _,v:=range x{if seen[v.KategoriPekerjaanID]{return ErrDuplicatePekerjaanKategori};seen[v.KategoriPekerjaanID]=true};return nil}
func(s *PekerjaanService)saveNotaris(tx *gorm.DB,id uint,q request.PekerjaanRequest,u uint,n time.Time)error{for _,h:=range q.Harga{x:=&models.HargaPekerjaanNotaris{PekerjaanNotarisID:id,Harga:h.Harga,KategoriPekerjaanID:h.KategoriPekerjaanID,EstimasiWaktu:h.EstimasiWaktu,CreatedBy:&u,CreatedAt:&n,Status:1};if e:=tx.Create(x).Error;e!=nil{return e}};for _,p:=range q.Proses{x:=&models.ProsesPekerjaanNotaris{PekerjaanNotarisID:id,Nama:p.Nama,Detail:p.Detail,CreatedBy:&u,CreatedAt:&n,Status:1};if e:=tx.Create(x).Error;e!=nil{return e};for _,a:=range p.Atribut{if a.Atribut==""{continue};z:=&models.AtributPekerjaanNotaris{PekerjaanNotarisID:id,ProsesPekerjaanNotarisID:x.ID,Atribut:a.Atribut,CreatedBy:&u,CreatedAt:&n,Status:1};if e:=tx.Create(z).Error;e!=nil{return e}}};return nil}
func(s *PekerjaanService)savePPAT(tx *gorm.DB,id uint,q request.PekerjaanRequest,u uint,n time.Time)error{for _,h:=range q.Harga{x:=&models.HargaPekerjaanPPAT{PekerjaanPPATID:id,Harga:h.Harga,KategoriPekerjaanID:h.KategoriPekerjaanID,EstimasiWaktu:h.EstimasiWaktu,CreatedBy:&u,CreatedAt:&n,Status:1};if e:=tx.Create(x).Error;e!=nil{return e}};for _,p:=range q.Proses{x:=&models.ProsesPekerjaanPPAT{PekerjaanPPATID:id,Nama:p.Nama,Detail:p.Detail,CreatedBy:&u,CreatedAt:&n,Status:1};if e:=tx.Create(x).Error;e!=nil{return e};for _,a:=range p.Atribut{if a.Atribut==""{continue};z:=&models.AtributPekerjaanPPAT{PekerjaanPPATID:id,ProsesPekerjaanPPATID:x.ID,Atribut:a.Atribut,CreatedBy:&u,CreatedAt:&n,Status:1};if e:=tx.Create(z).Error;e!=nil{return e}}};return nil}
func(s *PekerjaanService)attachNotaris(x []models.PekerjaanNotaris)([]PekerjaanResponse,error){out:=make([]PekerjaanResponse,0,len(x));for _,p:=range x{var h []models.HargaPekerjaanNotaris;var pr []models.ProsesPekerjaanNotaris;if e:=database.DB.Where("pekerjaan_notaris_id=?",p.ID).Find(&h).Error;e!=nil{return nil,e};if e:=database.DB.Where("pekerjaan_notaris_id=?",p.ID).Find(&pr).Error;e!=nil{return nil,e};o:=PekerjaanResponse{ID:p.ID,Nama:p.Nama,Harga:[]PekerjaanHargaResponse{},Proses:[]PekerjaanProsesResponse{}};for _,v:=range h{o.Harga=append(o.Harga,PekerjaanHargaResponse{ID:v.ID,Harga:v.Harga,KategoriPekerjaanID:v.KategoriPekerjaanID,EstimasiWaktu:v.EstimasiWaktu})};for _,v:=range pr{var a []models.AtributPekerjaanNotaris;if e:=database.DB.Where("proses_pekerjaan_notaris_id=?",v.ID).Find(&a).Error;e!=nil{return nil,e};z:=PekerjaanProsesResponse{ID:v.ID,Nama:v.Nama,Detail:v.Detail,Atribut:[]PekerjaanAtributResponse{}};for _,w:=range a{z.Atribut=append(z.Atribut,PekerjaanAtributResponse{ID:w.ID,Atribut:w.Atribut})};o.Proses=append(o.Proses,z)};out=append(out,o)};return out,nil}
func(s *PekerjaanService)attachPPAT(x []models.PekerjaanPPAT)([]PekerjaanResponse,error){out:=make([]PekerjaanResponse,0,len(x));for _,p:=range x{var h []models.HargaPekerjaanPPAT;var pr []models.ProsesPekerjaanPPAT;if e:=database.DB.Where("pekerjaan_ppat_id=?",p.ID).Find(&h).Error;e!=nil{return nil,e};if e:=database.DB.Where("pekerjaan_ppat_id=?",p.ID).Find(&pr).Error;e!=nil{return nil,e};o:=PekerjaanResponse{ID:p.ID,Nama:p.Nama,Harga:[]PekerjaanHargaResponse{},Proses:[]PekerjaanProsesResponse{}};for _,v:=range h{o.Harga=append(o.Harga,PekerjaanHargaResponse{ID:v.ID,Harga:v.Harga,KategoriPekerjaanID:v.KategoriPekerjaanID,EstimasiWaktu:v.EstimasiWaktu})};for _,v:=range pr{var a []models.AtributPekerjaanPPAT;if e:=database.DB.Where("proses_pekerjaan_ppat_id=?",v.ID).Find(&a).Error;e!=nil{return nil,e};z:=PekerjaanProsesResponse{ID:v.ID,Nama:v.Nama,Detail:v.Detail,Atribut:[]PekerjaanAtributResponse{}};for _,w:=range a{z.Atribut=append(z.Atribut,PekerjaanAtributResponse{ID:w.ID,Atribut:w.Atribut})};o.Proses=append(o.Proses,z)};out=append(out,o)};return out,nil}
